HL7/fhir-qi-core

pages/AdverseEvent.html, pages/AllergyIntolerance.html, pages/Assessment.html, pages/CareExperience.html, pages/CareGoal.html, pages/Communication.html, pages/ConditionDiagnosisProblem.html, pages/Device.html, pages/DiagnosticStudy.html, pages/Encounter.html, pages/FamilyHistory.html, pages/Immunization.html, pages/IndividualCharacteristic.html, pages/LaboratoryTest.html, pages/Medication.html, pages/Participation.html, pages/PhysicalExam.html, pages/Procedure.html, pages/Substance.html, pages/Symptom.html, pages/qdm-to-qicore.html
Note: Some content on the confluence page did not have an equivalent on the FHIR site. In the interest of preserving the original structure, I left this content out for now. But if it would be helpful to come back and make new pages to make the FHIR site as similar to the confluence page as possible, I am happy to do so!
=> Updated Mapping Content

pages/patterns.html
Also fixed anchor links and a mismatched tag
=> Added examples to QI Core IG

resources/qicore.xml
IG not building due to this issue
=> Fixed canonical urls for example resource entries

pages/qdm-to-qicore.md, resources/communication-negation-example.xml, resources/devicerequest-negation-example.xml, resources/immunization-negation-example.xml, resources/immunizationnotdone-profile-spreadsheet.xml, resources/medicationdispensenotdone-profile-spreadsheet.xml, resources/medicationrequest-negation-example.xml, resources/mednotadministered-profile-spreadsheet.xml, resources/observation-negation-example.xml, resources/observationnotdone-profile-spreadsheet.xml, resources/procedure-negation-example.xml, resources/procedurenotdone-profile-spreadsheet.xml, resources/servicenotrequested-profile-spreadsheet.xml, resources/servicerequest-negation-example.xml
Fixing valueset-reference extension for Coding context. Adding to examples where missing.
Still an issue for profiles with choice types:
- DeviceNotRequested
- MedicationAdministrationNotDone
- MedicaitonDispenseNotDone
- MedicationNotRequested
=> QA: valueset-reference

pages/_includes/qicore-medicationrequest-ex.html, resources/immunization-profile-spreadsheet.xml, resources/medicationrequest-cmd-example.xml, resources/medicationrequest-profile-spreadsheet.xml, resources/organization-profile-spreadsheet.xml, resources/practitioner-profile-spreadsheet.xml, resources/qicore.xml
Immunization.occurrence remove the String choice
Add must support for several MedicationRequest attributes, plus CMD
example
Add CCN identifier slice to Practitioner and Organization
=> FHIR-26407, FHIR-28286, FHIR-28157 (under CQF-599)

pages/_includes/qicore-mednotadministered-ex.html, resources/medicationadministration-negation-with-code-example.xml, resources/medicationdispense-profile-spreadsheet.xml, resources/mednotadministered-profile-spreadsheet.xml, resources/qicore.xml
=> FHIR-31609

input/pages/index.md
Added solution detailed in https://jira.hl7.org/browse/FHIR-38315
=> FHIR-38315 - Adjusted verbiage according to requirement.

input/pages/patterns.md
https://jira.hl7.org/browse/FHIR-38112
=> FHIR-38112 - Blood Pressure Example update

input/intro-notes/StructureDefinition-qicore-bodystructure-intro.xml, input/intro-notes/StructureDefinition-qicore-communicationnotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-device-intro.xml, input/intro-notes/StructureDefinition-qicore-devicenotrequested-intro.xml, input/intro-notes/StructureDefinition-qicore-immunizationnotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-medicationadministrationnotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-medicationdispensedeclined-intro.xml, input/intro-notes/StructureDefinition-qicore-medicationnotrequested-intro.xml, input/intro-notes/StructureDefinition-qicore-procedurenotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-servicenotrequested-intro.xml, input/pages/examples.md, input/pages/index.md, input/pages/modelinfo.md, input/profiles/StructureDefinition-qicore-adverseevent.json, input/profiles/StructureDefinition-qicore-communication.json, input/profiles/StructureDefinition-qicore-communicationrequest.json, input/profiles/StructureDefinition-qicore-devicerequest.json, input/profiles/StructureDefinition-qicore-deviceusestatement.json, input/profiles/StructureDefinition-qicore-imagingstudy.json, input/profiles/StructureDefinition-qicore-medicationadministration.json, input/profiles/StructureDefinition-qicore-observation.json, input/profiles/StructureDefinition-qicore-observationcancelled.json, input/profiles/StructureDefinition-qicore-procedure.json, input/profiles/StructureDefinition-qicore-questionnaireresponse.json, input/profiles/StructureDefinition-qicore-servicenotrequested.json, input/profiles/StructureDefinition-qicore-servicerequest.json, input/profiles/StructureDefinition-qicore-specimen.json
Updated wording to ProcedureNotDone from Procedure, Not Performed -> The following should be FHIR-40474 not FHIR-40473
=> FHIR-40477,40479,40480,40481,40483

input/profiles/StructureDefinition-qicore-goal.json
https://jira.hl7.org/browse/FHIR-41537
=> FHIR-41537: Update QI-Core Goal profile to align with US Core 6.1.0 and to simplify

input/profiles/StructureDefinition-qicore-devicerequest.json
Removed the following elements from the differential list in order to remove them from the Key Elements table view:
DeviceRequest.encounter
DeviceRequest.[occurence[x]]
DeviceRequet.requester
DeviceRequest.performer
DeviceRequest.reasonReference
=> FHIR-41467 Removed differential elements

input/profiles/StructureDefinition-qicore-devicerequest.json, input/profiles/StructureDefinition-qicore-immunization.json
Removed the following from the differential elements in order to remove from the Key Elements table view:
Immunization.encounter
Immunization.location
Immunization.manufacturer
Immunization.site
Immunization.route
Immunization.doseQuantity
Immunization.reasonCode
Immunization.reaction
Immunization.modifierExtension
Immunization.detail
Immunization.protocolApplied
Immunization.modiferExtension
Immunization.authority
Immunization.[doseNumber[x]]
Changed the cardinality of differential element Immunization.statusReason from 0..0 to 0..1 so that it will appear in the Key Elements table view.
See: https://jira.hl7.org/browse/FHIR-41468 Adjust QI-Core Immunization must supports
=> Fhir 41468 Adjust QI-Core Immunization must supports

input/profiles/StructureDefinition-qicore-procedurenotdone.json
Removed the following from the differential elements in order to remove from the Key Elements table view:
ProcedureNotDone.encounter
See: https://jira.hl7.org/browse/FHIR-41481 Adjust QI-Core ProcedureNotDone must supports
=> FHIR-41481 Adjust Procedure Not Done must supports

input/profiles/StructureDefinition-qicore-practitioner.json
Added the identifier:All Slices element from US Core Practitioner to QICore Practitioner differentials
Removed qualitication element. from QICore Practitioner differentials
=> FHIR-41541Update QI-Core Practitioner profile to align with US Core 6.1.0

input/profiles/StructureDefinition-qicore-immunizationnotdone.json
https://jira.hl7.org/browse/FHIR-41528
=> FHIR-41528: QI Core Version 6.0 ImmunizationNotDone Update recommendations

input/profiles/StructureDefinition-qicore-location.json
https://jira.hl7.org/browse/FHIR-41538
=> FHIR-41538: Update QI-Core to align with US Core Location profile

input/pages/index.md, input/profiles/StructureDefinition-qicore-encounter.json
https://jira.hl7.org/browse/FHIR-41265
=> Fhir 41265: remove Must Support for Encounter.diagnosis and its respective elements

input/profiles/StructureDefinition-qicore-medication.json, input/profiles/StructureDefinition-qicore-medicationadministration.json, input/profiles/StructureDefinition-qicore-medicationadministrationnotdone.json, input/profiles/StructureDefinition-qicore-medicationdispense.json, input/profiles/StructureDefinition-qicore-medicationdispensedeclilned.json, input/profiles/StructureDefinition-qicore-medicationnotrequested.json, input/profiles/StructureDefinition-qicore-medicationrequest.json
FHIR-41539
FHIR-41511
FHIR-41474
FHIR-41473
FHIR-41472
FHIR-41471
FHIR-41470
=> QI Core comment resolutions for Key elements and MS flags

input/qicore.xml
https://jira.hl7.org/browse/FHIR-42446
=> FHIR-42446 - Applied changes to MedicationAdministration example

input/pages/qdm-to-qicore.md
https://jira.hl7.org/browse/FHIR-42370
=> FHIR-42370 - applied changes to qdm-to-qicore

input/profiles/StructureDefinition-qicore-taskrejected.json
https://jira.hl7.org/browse/FHIR-41934
=> FHIR-41934 - Applied changes to StructureDefinition-qicore-taskrejected

input/pages/index.md
https://jira.hl7.org/browse/FHIR-41845
=> FHIR-41845 - Applied changes to index

input/data/new_items.yml, input/pages/changes.md, input/pages/extensions.md, input/pages/index.md, input/pages/profiles.md, input/pages/qdm-to-qicore.md
https://jira.hl7.org/browse/FHIR-42667
https://jira.hl7.org/browse/FHIR-42987
https://jira.hl7.org/browse/FHIR-42372
https://jira.hl7.org/browse/FHIR-42009
and internal ICF QA edits:  https://icf.atlassian.net/browse/CQF-2031:
- Added em-dash character centered in each empty cell in the profiles table.
- Corrected display of ClaimResponse base name
- Removed STU Note as presented in resolution.
=> Fhir 42009 et al

input/pages/index.md
https://jira.hl7.org/browse/FHIR-44743
=> TLS 1.1 deprecated to BCP195

input/profiles/StructureDefinition-qicore-medicationnotrequested.json
https://jira.hl7.org/browse/FHIR-44737
=> MedicationNotRequested binding change

input/pages/changes.md, input/profiles/StructureDefinition-qicore-adverseevent.json
=> FHIR-45693 limit subject reference in AdverseEvent to patient 

input/pages/index.md
https://jira.hl7.org/browse/FHIR-14994
=> section 1.17 second bullet change

input/pages/modelinfo.md, input/pages/negation.md, input/pages/patterns.md
https://jira.hl7.org/browse/FHIR-44738
=> consider refactoring to using cql IG

input/pages/terminology.md
https://jira.hl7.org/browse/FHIR-44808
=> guidance section link updated

input/pages/changes.md, input/profiles/StructureDefinition-qicore-medicationrequest.json
https://jira.hl7.org/browse/FHIR-46040
QICore MedicationRequest prohibits reportedBoolean
=> FHIR-46040 QICore MedicationRequest prohibits reportedBoolean

input/pages/index.md
https://jira.hl7.org/browse/FHIR-45360
=> FHIR-45360: Update QI-Core references to USCDI

input/pages/index.md
https://jira.hl7.org/browse/FHIR-46030
=> Applied note to balloters

input/pages/changes.md, input/profiles/StructureDefinition-qicore-claim.json
https://jira.hl7.org/browse/FHIR-45959
Changed QI-Core in short descriptions to QI.
=> Update QI-Core Claim to include key elements for present on admission and principal diagnosis

input/pages/index.md
https://jira.hl7.org/browse/FHIR-45947
=> FHIR-45947: Updated index

input/profiles/StructureDefinition-qicore-servicenotrequested.json, input/profiles/StructureDefinition-qicore-servicerequest.json
https://jira.hl7.org/browse/FHIR-45432
=> FHIR-45432: Updated ServiceRequest and ServiceNotRequested

input/profiles/StructureDefinition-qicore-procedure.json, input/profiles/StructureDefinition-qicore-procedurenotdone.json
https://jira.hl7.org/browse/FHIR-45429
=> FHIR-45429: Update QI-Core Procedure and ProcedureNotDone

input/pages/changes.md, input/profiles/StructureDefinition-qicore-condition-encounter-diagnosis.json, input/profiles/StructureDefinition-qicore-condition-problems-health-concerns.json
https://jira.hl7.org/browse/FHIR-45396
=> FHIR-45396 Update QI-Core Condition Encounter Diagnosis and QI-Core Condition Problems and Health Concerns Profiles to build off of US Core 7.0

input/pages/changes.md, input/profiles/StructureDefinition-qicore-encounter.json
https://jira.hl7.org/browse/FHIR-45398
=> FHIR-45398 Update Qi-core to build off of US-core 7.0 for encounter profile

input/pages/changes.md, input/profiles/StructureDefinition-qicore-diagnosticreport-lab.json
https://jira.hl7.org/browse/FHIR-45397
=> FHIR-45397 Update QICore DiagnosticReport Profile for Laboratory Results 

input/pages/changes.md, input/profiles/StructureDefinition-qicore-medicationdispense.json, input/profiles/StructureDefinition-qicore-medicationdispensedeclined.json
https://jira.hl7.org/browse/FHIR-45402
=> FHIR-45402 Update QI-Core Medication and QI-Core MedicationDispense

input/pages/changes.md, input/profiles/StructureDefinition-qicore-immunizationnotdone.json
https://jira.hl7.org/browse/FHIR-45400
=> FHIR-45400 Update QI-Core Immunization, QI-Core ImmunizationNotDone profiles to build from US 7.0 Core Immunization Profile

input/pages/changes.md, input/profiles/StructureDefinition-qicore-careplan.json, input/profiles/StructureDefinition-qicore-careteam.json
https://jira.hl7.org/browse/FHIR-45395
=> FHIR-45395 Update AllergyIntolerance, CarePlan, CareTeam, and Coverage profiles to address US Core 7.0

input/data/new_items.yml, input/pages/changes.md, input/resources/devicerequest-example.xml, input/resources/devicerequest-negation-example.xml, input/resources/devicerequest-negation-with-code-example.xml, input/tests/QICoreCommonTests/example/DeviceRequest/DeviceRequest-negation-example.json
Screenshot showing QA 0 errors/warnings for edited examples attached.
=> Dd 46669 device request negation edits

input/profiles/StructureDefinition-qicore-condition-encounter-diagnosis.json
Update QI-Core ConditionEncounterDiagnosis such that the subject reference has a MS on Patient - (QICorePatient)
QA result:
=> FHIR-47857

input/profiles/Structuredefinition-qicore-coverage.json
Change QI-Core Coverage.policyHolder Key Element to (QI) 
QA result:
=> FHIR-47862

input/profiles/StructureDefinition-qicore-diagnosticreport-lab.json, input/profiles/StructureDefinition-qicore-diagnosticreport-note.json
Add (QI) tag: 
QI-Core DiagnosticReport for LaboratoryResultsReporting - .code, .encounter, .issued, .status
QI-Core DiagnosticReport for Note Exchange - .status, .imagingStudy
QA results:
=> FHIR-47870

input/pages/profiles.md
Update to QI Core Profile Headings w/Current Version
QA result: N/A
=> FHIR-47398

input/pages/index.md
Correct duplicate content error Under MustSupport Flag
QA results: N/A
=> FHIR-47407

input/intro-notes/StructureDefinition-qicore-claim-intro.xml, input/intro-notes/StructureDefinition-qicore-communicationnotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-devicenotrequested-intro.xml, input/intro-notes/StructureDefinition-qicore-immunizationnotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-keyelement-intro.xml, input/intro-notes/StructureDefinition-qicore-medicationadministration-intro.xml, input/intro-notes/StructureDefinition-qicore-medicationadministrationnotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-medicationdispense-intro.xml, input/intro-notes/StructureDefinition-qicore-nonpatient-observation-intro.xml, input/intro-notes/StructureDefinition-qicore-observation-lab-intro.xml, input/intro-notes/StructureDefinition-qicore-observationcancelled-intro.xml, input/intro-notes/StructureDefinition-qicore-procedurenotdone-intro.xml, input/intro-notes/StructureDefinition-qicore-relatedperson-intro.xml, input/intro-notes/StructureDefinition-qicore-servicenotrequested-intro.xml, input/pages/qi-elements.md
This was ran off latest master branch from parent
=> Intro Generation: Modified script to create missing intro files.

input/profiles/StructureDefinition-qicore-adverseevent.json
Replace existing 13.2.1 Adverse Event first paragraph with language directly from the FHIR definition
QA result;
=> FHIR-47815

input/pages/changes.md, input/profiles/StructureDefinition-qicore-condition-encounter-diagnosis.json
https://jira.hl7.org/browse/FHIR-47540
=> Fhir 47540

input/pages/changes.md, input/pages/modelinfo.md
https://jira.hl7.org/browse/FHIR-47411
No QA photo needed for this one.
Link changes
=> FHIR-47411 

input/profiles/StructureDefinition-qicore-devicerequest.json
QI-Core DeviceRequest codeReference should be QICoreDevice not Device
https://jira.hl7.org/browse/FHIR-46655
New PR as last branch had issues. 
QA, passed
=> FHIR-46655

input/profiles/StructureDefinition-qicore-immunization.json, input/profiles/StructureDefinition-qicore-immunizationnotdone.json
https://jira.hl7.org/browse/FHIR-46656
Immunization and ImmunizationNotDone should reference QICoreEncounter and QICoreLocation
New PR, closed previous branch
QA passed
=> FHIR-46656

input/profiles/StructureDefinition-qicore-communication.json
https://jira.hl7.org/browse/FHIR-47852
=> FHIR-47852: Added QI Core CareTeam to Communication.recipient references

input/profiles/StructureDefinition-qicore-allergyintolerance.json, input/profiles/StructureDefinition-qicore-condition-encounter-diagnosis.json, input/profiles/StructureDefinition-qicore-condition-problems-health-concerns.json, input/profiles/StructureDefinition-qicore-encounter.json, input/profiles/StructureDefinition-qicore-medicationnotrequested.json, input/profiles/StructureDefinition-qicore-medicationrequested.json
https://jira.hl7.org/browse/FHIR-47759
=> FHIR-47759: Added (QI) key element extensions to various files

input/profiles/StructureDefinition-qicore-medicationadministrationnotdone.json, input/profiles/StructureDefinition-qicore-procedure.json
https://jira.hl7.org/browse/FHIR-47751
=> FHIR-47751: implictRules removed as a QI element

input/profiles/StructureDefinition-qicore-simple-observation.json
Remove QI tag from partOf
QA result:
=> FHIR-48099

input/pages/index.md
https://jira.hl7.org/browse/FHIR-47409
adding link to BPC195
No qa needed
=> FHIR-47409

input/pages/changes.md
https://jira.hl7.org/browse/FHIR-46872
No qa changes
=> fixing typo

input/profiles/StructureDefinition-qicore-task.json, input/profiles/StructureDefinition-qicore-taskrejected.json
Make for element a qi element on task resources
https://jira.hl7.org/browse/FHIR-47752
No qa errors, only warnings
=> FHIR-47752

input/pages/changes.md, input/profiles/StructureDefinition-qicore-location.json
QICore Location primary code path
https://jira.hl7.org/browse/FHIR-47880
=> FHIR-47880

input/intro-notes/StructureDefinition-qicore-careteam-intro.xml, input/intro-notes/StructureDefinition-qicore-familymemberhistory-intro.xml, input/pages/changes.md, input/pages/qi-elements.md, input/profiles/StructureDefinition-qicore-careteam.json, input/profiles/StructureDefinition-qicore-familymemberhistory.json
Some Primary Code Path elements are not in the narrative element lists
https://jira.hl7.org/browse/FHIR-47744
=> Fhir 47744 updated

input/data/new_items.yml, input/pages/changes.md, input/pages/index.md
Updated summary text on the index.md page as described in https://jira.hl7.org/browse/FHIR-47742.
(Text edits to markdown pages do not affect the QA report.)
=> FHIR-47742 Clarified summary text on index page
